More tests for `ReactiveInputStream`
cqfn/rio pull request #64
Opened 2021-08-20 06:54 UTC by olenagerasimova

Added test for `ReactiveInputStream` to obtain publisher (i need publisher so I can write to storage, not bytes count), when there are a lot of (100 is ok, 200 is not) write operation, everything stacks as usual.

2021-08-20 06:55 UTC, olenagerasimova commented
@g4s8 please, take a look

2021-08-20 07:49 UTC, g4s8 requested changes
@olenagerasimova please check my comment

2021-08-20 07:49 UTC, g4s8 commented on src/test/java/org/cqfn/rio/stream/ReactiveInputStreamTest.java
> +            res = new ReactiveInputStream(new PipedInputStream(newout)).read(Buffers.Standard.K1);
@olenagerasimova publisher start reading data only after onSubscribe call, now you start reading it after writing data, so piped inputstream can't write it here. You need to start reading (to subscribe publisher) before writing any data for piped streams. Also, I'd not suggest using single here, because it's lazy instance: when you use futere, the async operation stats immediately but competes later, with single it starts after onSubscribe.

2021-08-20 08:42 UTC, olenagerasimova commented on src/test/java/org/cqfn/rio/stream/ReactiveInputStreamTest.java
> +            res = new ReactiveInputStream(new PipedInputStream(newout)).read(Buffers.Standard.K1);
@g4s8 as I said I need Publisher<ByteBuffer> as a result so I can write to storage. Subscriber with `CompletableFuture<Publisher<ByteBuffer>>` does not make a lot of sense or I do not see how to implement it, what should it do `onNext()`? 
I've tried to add Subscriber with `CompletableFuture<ByteBuffer>`, now it fails with `java.io.IOException: Pipe closed` after several write operations.

2021-08-24 07:42 UTC, olenagerasimova commented
@g4s8 please, merge, I've fixed the test

2021-08-24 07:59 UTC, g4s8 approved these changes
@olenagerasimova thanks

2021-08-24 08:00 UTC, merged